server:
  port: 7072

spring:
  datasource:
    username: postgres
    password: 123456789
    url: jdbc:postgresql://localhost:5432/Java10SocialUser
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secretKey: ${java10secretkey}
  issuer: ${java10issuer}